version: "2.1"

services:

  pg:
    image: postgres:12.2-alpine
    restart: always
    environment:
    # TODO: take these from environment
    - POSTGRES_PASSWORD=project
    - POSTGRES_USER=project
    - POSTGRES_DB=project

#  nginx:
#    image: nginx

  rabbitmq:
    image: rabbitmq:3.8.2

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    # TODO: take pg host and port from environment
    entrypoint: dockerize -wait tcp://pg:5432 -timeout 60s -- bash docker-entrypoint.sh
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    depends_on:
      - pg
    restart: on-failure
