version: "2.1"

services:

  pg:
    image: postgres:12.2-alpine
    restart: always
    environment:
    - POSTGRES_PASSWORD=test
    - POSTGRES_USER=test
    - POSTGRES_DB=test
    volumes:
    - postgres_volume:/var/lib/postgresql/data

  web:
    build:
      context: .
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - PG_HOST=pg
      - PG_PORT=5432
    depends_on:
      - pg
    restart: on-failure
    ports:
      - 8000:8000

  bg-tasks:
    build:
      context: .
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - PG_HOST=pg
      - PG_PORT=5432
    depends_on:
      - pg
    restart: always
    command: manage.py process_tasks


volumes:
  postgres_volume: